### ISSUE TITLE
Добавить в боковое меню ссылку на уведомления

### ISSUE THREAD

**Issue by Kildor** [1001v/New-VK-Settings#1]
Хотелось бы иметь возможность переходить из бокового меню на страницу https://new.vk.com/feed?section=notifications

**Comment by 1001v** [comment]
Добавил. Включается в "поведение интерфейса".

**Comment by Kildor** [comment]
Спасибо!
Два момента.
1. не работает, если в настройках меню выключена ссылка на документы. Лучше или вставлять его после #l_nwsf, либо через .appendTo('#side_bar ol');
2. Пункт меню всегда на русском, даже если интерфейс английский. Не уверен что с этим можно сделать что-то кроме как забить мультиязычные варианты, но в целом момент не критичный.

**Comment by 1001v** [comment]
1. Теперь пункт просто добавляется в конец ol.
2. Расширение предназначено для носителей русского языка, но в качестве исключения добавил поддержку английского.
