### ISSUE TITLE
Фиксированная шапка в URL, заканчивающихся на /im (Не только в сообщениях)

### ISSUE THREAD

**Issue by chayleaf** [1001v/New-VK-Settings#8]
Например, https://vk.com/feed/im. Или https://vk.com/*ссылка на паблик*/im (Открывает все записи с тегом #im@*ссылка на паблик*)

**Comment by 1001v** [comment]
Это не баг, а фича. Если бы в диалогах ездила шапка, были бы проблемы со скроллом.

**Comment by chayleaf** [comment]
Про диалоги я знаю, проблема в том, что она не только в сообщениях ездит

**Comment by chayleaf** [comment]
https://vk.com/feed/im - очевидно, не диалоги

**Comment by chayleaf** [comment]
Конечно, не очень важно, но баг присутствует

**Comment by chayleaf** [comment]
ща починю

**Comment by 1001v** [comment]
Мне, честно говоря, не удавалось найти страницу с там url, но ладно, пусть будет багом.

**Comment by 1001v** [comment]
Исправлено.

**Comment by chayleaf** [comment]
Не исправлено

**Comment by chayleaf** [comment]
![aaaasad](https://cloud.githubusercontent.com/assets/9590981/18785851/e98310fe-81c4-11e6-90ac-b91945d1d116.png)
